### ISSUE TITLE
Unable to initialize text.SimpleQA(INDEXDIR)

### ISSUE THREAD

**Issue by logisticDigressionSplitter** [amaiya/ktrain#127]
ktrain =  0.14.1
tensorflow = 2.1.0

/usr/local/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py in _variable_handle_from_shape_and_dtype(shape, dtype, shared_name, name, graph_mode, initial_value)
    166     handle_data = cpp_shape_inference_pb2.CppShapeInferenceResult.HandleData()
    167     handle_data.is_set = True
--> 168     handle_data.shape_and_type.append(
    169         cpp_shape_inference_pb2.CppShapeInferenceResult.HandleShapeAndType(
    170             shape=shape.as_proto(), dtype=dtype.as_datatype_enum))

AttributeError: 'google.protobuf.pyext._message.RepeatedCompositeCo' object has no attribute 'append'

**Comment by amaiya** [comment]
You haven't shared what platform your'e using.  It works correctly on both a fresh Ubuntu 18.04 system and also on Google Colab.  See [this Colab notebook](https://colab.research.google.com/drive/1tcsEQ7igx7lw_R0Pfpmsg9Wf3DEXyOvk).

Perhaps try upgrading protobuf package, as described in [this post](https://stackoverflow.com/questions/58343293/attributeerror-google-protobuf-pyext-message-repeatedcompositeco-object-has).
